---
  extends: airbnb-typescript
  parser: '@typescript-eslint/parser'
  parserOptions:
    ecmaVersion: 6
    sourceType: module
  env:
    browser: true
    mocha: true

  plugins:
    - '@typescript-eslint'

  rules:
    max-len: ["error", 120]
    class-methods-use-this: 0
    quotes: ["error", "single"]
    import/no-default-export: 0
    import/prefer-default-export: "off"
    no-constant-condition: ["error", {"checkLoops": false}]
    object-property-newline: 0
    lines-between-class-members: 0
    max-classes-per-file: 0
    spaced-comment: 0
    nonblock-statement-body-position: 0
    object-curly-spacing: ["error", "never"]
    function-paren-newline: 0
    object-curly-newline: 0
    one-var: 0
    vars-on-top: 0
    curly: 0
    one-var-declaration-per-line: 0
    import/no-extraneous-dependencies: 0
    import/extensions: 0
    import/no-cycle: 0
    global-require: 0
    new-parens: 0
    guard-for-in: 0
    no-restricted-syntax: 0
    no-continue: 0
    no-param-reassign: 0
    no-bitwise: 0
    no-plusplus: 0
    no-underscore-dangle: 0
    no-console: ["error", {"allow": ["warn", "error", "info"]}]
    no-use-before-define: ["error", {"variables": false}]
    no-unused-expressions: ["error", {"allowTaggedTemplates": true, "allowShortCircuit": true}]
    camelcase: ["error", {allow: ["^UNSAFE_"], properties: "never"}]
